# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.pst_window_query <- function(Y, start_offset, end_offset, n_starts, order, lo, hi, parity) {
    .Call(`_musclePST_pst_window_query`, Y, start_offset, end_offset, n_starts, order, lo, hi, parity)
}

.MUSCLE <- function(Y, q, beta, test, details) {
    .Call(`_musclePST_MUSCLE`, Y, q, beta, test, details)
}

.DMUSCLE <- function(Y, q, beta, lag, test, details) {
    .Call(`_musclePST_DMUSCLE`, Y, q, beta, lag, test, details)
}

.MMUSCLE <- function(Y, q_matrix, beta_vec, test, details) {
    .Call(`_musclePST_MMUSCLE`, Y, q_matrix, beta_vec, test, details)
}

.MUSCLE_FULL <- function(Y, q, beta, test, details) {
    .Call(`_musclePST_MUSCLE_FULL`, Y, q, beta, test, details)
}

.DMUSCLE_FULL <- function(Y, q, beta, lag, test, details) {
    .Call(`_musclePST_DMUSCLE_FULL`, Y, q, beta, lag, test, details)
}

.simulQuantile_MUSCLE <- function(p, n, beta) {
    .Call(`_musclePST_simulQuantile_MUSCLE`, p, n, beta)
}

.logg <- function(x) {
    .Call(`_musclePST_logg`, x)
}

.simulQuantile_DMUSCLE <- function(X, ACF, n) {
    .Call(`_musclePST_simulQuantile_DMUSCLE`, X, ACF, n)
}

