# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.pst_window_query <- function(Y, start_offset, end_offset, n_starts, order, lo, hi, parity) {
    .Call(`_muscle_pst_window_query`, Y, start_offset, end_offset, n_starts, order, lo, hi, parity)
}

.MUSCLE_backend <- function(Y, q, beta, test, details, backend) {
    .Call(`_muscle_MUSCLE`, Y, q, beta, test, details, backend)
}

.DMUSCLE_backend <- function(Y, q, beta, lag, test, details, backend) {
    .Call(`_muscle_DMUSCLE`, Y, q, beta, lag, test, details, backend)
}

.MMUSCLE_backend <- function(Y, q_matrix, beta_vec, test, details, backend) {
    .Call(`_muscle_MMUSCLE`, Y, q_matrix, beta_vec, test, details, backend)
}

.MUSCLE_FULL_backend <- function(Y, q, beta, test, details, backend) {
    .Call(`_muscle_MUSCLE_FULL`, Y, q, beta, test, details, backend)
}

.DMUSCLE_FULL_backend <- function(Y, q, beta, lag, test, details, backend) {
    .Call(`_muscle_DMUSCLE_FULL`, Y, q, beta, lag, test, details, backend)
}

.simulQuantile_MUSCLE <- function(p, n, beta) {
    .Call(`_muscle_simulQuantile_MUSCLE`, p, n, beta)
}

.logg <- function(x) {
    .Call(`_muscle_logg`, x)
}

.simulQuantile_DMUSCLE <- function(X, ACF, n) {
    .Call(`_muscle_simulQuantile_DMUSCLE`, X, ACF, n)
}
