# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.MUSCLE <- function(Y, q, beta, test, details) {
    .Call(`_muscle_MUSCLE`, Y, q, beta, test, details)
}

.DMUSCLE <- function(Y, q, beta, lag, test, details) {
    .Call(`_muscle_DMUSCLE`, Y, q, beta, lag, test, details)
}

.MMUSCLE <- function(Y, q_matrix, beta_vec, test, details) {
    .Call(`_muscle_MMUSCLE`, Y, q_matrix, beta_vec, test, details)
}

.MUSCLE_FULL <- function(Y, q, beta, test, details) {
    .Call(`_muscle_MUSCLE_FULL`, Y, q, beta, test, details)
}

.DMUSCLE_FULL <- function(Y, q, beta, lag, test, details) {
    .Call(`_muscle_DMUSCLE_FULL`, Y, q, beta, lag, test, details)
}

.simulQuantile_MUSCLE <- function(p, n, beta) {
    .Call(`_muscle_simulQuantile_MUSCLE`, p, n, beta)
}

.logg <- function(x) {
    .Call(`_muscle_logg`, x)
}

.simulQuantile_DMUSCLE <- function(X, ACF, n) {
    .Call(`_muscle_simulQuantile_DMUSCLE`, X, ACF, n)
}

